# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/crystallang/crystal/
image: "crystallang/crystal:latest"

# Cache shards in between builds
cache:
  paths:
    - lib
    - bin

before_script:
  - crystal -v
  - shards

spec:
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode_spec.cr spec/extensions_spec.cr
  artifacts:
    when: always
    paths:
      - output.xml
    reports:
      junit: output.xml

spec-angles:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/angles/**

spec-matrices:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/matrices/matrix_spec.cr

spec-matrix1:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/matrices/matrix1*_spec.cr

spec-matrix2:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/matrices/matrix2*_spec.cr

spec-matrix3:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/matrices/matrix3*_spec.cr

spec-matrix4:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/matricesFix paths again/matrix4*_spec.cr

spec-vectors:
  extends: spec
  script:
    - crystal spec --error-on-warnings --junit_output=. spec/geode/vectors/**

format:
  script:
    - crystal tool format --check

lint:
  script:
    - bin/ameba

pages:
  stage: deploy
  script:
    - crystal docs
    - mv docs/ public/
  artifacts:
    paths:
      - public
  only:
    - master
